//
// FCMAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

open class FCMAPI {

    /**
     FCM Validation
     
     - parameter fCMValidationInput: (body) Unique AppID of the user to get 
     - returns: APIThread
     */
    @available(macOS 10.15, iOS 13.0, tvOS 13.0, watchOS 6.0, *)
    open class func fCMValidationPost(fCMValidationInput: FCMValidationInput) async throws -> APIThread {
        return try await fCMValidationPostWithRequestBuilder(fCMValidationInput: fCMValidationInput).execute().body
    }

    /**
     FCM Validation
     - POST /fcmValidation
     - Endpoint to just validate FCM notification by App teams
     - API Key:
       - type: apiKey X-Device-ID (HEADER)
       - name: DeviceId
     - API Key:
       - type: apiKey X-API-Key (HEADER)
       - name: ApiKeyAuth
     - BASIC:
       - type: http
       - name: BearerAuth
     - parameter fCMValidationInput: (body) Unique AppID of the user to get 
     - returns: RequestBuilder<APIThread> 
     */
    open class func fCMValidationPostWithRequestBuilder(fCMValidationInput: FCMValidationInput) -> RequestBuilder<APIThread> {
        let localVariablePath = "/fcmValidation"
        let localVariableURLString = InAppChatAPI.basePath + localVariablePath
        let localVariableParameters = JSONEncodingHelper.encodingParameters(forEncodableObject: fCMValidationInput)

        let localVariableUrlComponents = URLComponents(string: localVariableURLString)

        let localVariableNillableHeaders: [String: Any?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<APIThread>.Type = InAppChatAPI.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "POST", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true)
    }
}
