//
// Auth.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** An auth response */
public struct Auth: Codable, JSONEncodable, Hashable {

    public var token: Token
    public var user: APIUser
    public var notificationSettings: NotificationSettings?

    public init(token: Token, user: APIUser, notificationSettings: NotificationSettings? = nil) {
        self.token = token
        self.user = user
        self.notificationSettings = notificationSettings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case token
        case user
        case notificationSettings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(token, forKey: .token)
        try container.encode(user, forKey: .user)
        try container.encodeIfPresent(notificationSettings, forKey: .notificationSettings)
    }
}

