//
// AutoDeleteSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AutoDeleteSettings: Codable, JSONEncodable, Hashable {

    /** Enabled or not */
    public var enabled: Bool?
    /** SHould be deleted after this many miliseconds */
    public var deleteAfterMiliSeconds: Double?

    public init(enabled: Bool? = nil, deleteAfterMiliSeconds: Double? = nil) {
        self.enabled = enabled
        self.deleteAfterMiliSeconds = deleteAfterMiliSeconds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case enabled
        case deleteAfterMiliSeconds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(enabled, forKey: .enabled)
        try container.encodeIfPresent(deleteAfterMiliSeconds, forKey: .deleteAfterMiliSeconds)
    }
}

