//
// AvailabilityEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A user&#39;s availability changed */
public struct AvailabilityEvent: Codable, JSONEncodable, Hashable {

    /** The user ID */
    public var eRTCUserId: String
    public var availabilityStatus: AvailabilityStatus

    public init(eRTCUserId: String, availabilityStatus: AvailabilityStatus) {
        self.eRTCUserId = eRTCUserId
        self.availabilityStatus = availabilityStatus
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eRTCUserId
        case availabilityStatus
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eRTCUserId, forKey: .eRTCUserId)
        try container.encode(availabilityStatus, forKey: .availabilityStatus)
    }
}

