//
// ChatReportEventEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatReportEventEvent: Codable, JSONEncodable, Hashable {

    public var eventType: String
    public var eventData: ChatReportEventEventEventData

    public init(eventType: String, eventData: ChatReportEventEventEventData) {
        self.eventType = eventType
        self.eventData = eventData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventType
        case eventData
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventType, forKey: .eventType)
        try container.encode(eventData, forKey: .eventData)
    }
}

