//
// ChatStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatStatus: Codable, JSONEncodable, Hashable {

    public var returnCode: SenderReturnCode
    public var retryRequired: Bool
    public var keyList: [ChatStatusKeyListInner]

    public init(returnCode: SenderReturnCode, retryRequired: Bool, keyList: [ChatStatusKeyListInner]) {
        self.returnCode = returnCode
        self.retryRequired = retryRequired
        self.keyList = keyList
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case returnCode
        case retryRequired
        case keyList
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(returnCode, forKey: .returnCode)
        try container.encode(retryRequired, forKey: .retryRequired)
        try container.encode(keyList, forKey: .keyList)
    }
}

