//
// ChatStatusKeyListInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatStatusKeyListInner: Codable, JSONEncodable, Hashable {

    /** Key identifier. */
    public var keyId: String
    /** Device identifier. */
    public var deviceId: String
    /** public Key of associated device */
    public var publicKey: String
    /** user eRTCUserId. */
    public var eRTCUserId: String
    public var returnCode: ReceiverReturnCode?

    public init(keyId: String, deviceId: String, publicKey: String, eRTCUserId: String, returnCode: ReceiverReturnCode? = nil) {
        self.keyId = keyId
        self.deviceId = deviceId
        self.publicKey = publicKey
        self.eRTCUserId = eRTCUserId
        self.returnCode = returnCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keyId
        case deviceId
        case publicKey
        case eRTCUserId
        case returnCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(keyId, forKey: .keyId)
        try container.encode(deviceId, forKey: .deviceId)
        try container.encode(publicKey, forKey: .publicKey)
        try container.encode(eRTCUserId, forKey: .eRTCUserId)
        try container.encodeIfPresent(returnCode, forKey: .returnCode)
    }
}

