//
// ChatSettingsDomainFilterInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatSettingsDomainFilterInner: Codable, JSONEncodable, Hashable {

    /** List of keywords */
    public var keywords: [String]?
    /** Type of action on match */
    public var actionType: String?

    public init(keywords: [String]? = nil, actionType: String? = nil) {
        self.keywords = keywords
        self.actionType = actionType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keywords
        case actionType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(keywords, forKey: .keywords)
        try container.encodeIfPresent(actionType, forKey: .actionType)
    }
}

