//
// ChatReportEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Chat report updated event */
public struct ChatReportEvent: Codable, JSONEncodable, Hashable {

    public var chatReportId: String?
    public var event: ChatReportEventEvent?

    public init(chatReportId: String? = nil, event: ChatReportEventEvent? = nil) {
        self.chatReportId = chatReportId
        self.event = event
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chatReportId
        case event
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(chatReportId, forKey: .chatReportId)
        try container.encodeIfPresent(event, forKey: .event)
    }
}

