//
// ChatReportEventEventEventData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatReportEventEventEventData: Codable, JSONEncodable, Hashable {

    public var chatReport: Report

    public init(chatReport: Report) {
        self.chatReport = chatReport
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case chatReport
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(chatReport, forKey: .chatReport)
    }
}

