//
// ChatSettings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ChatSettings: Codable, JSONEncodable, Hashable {

    /** Tenant id */
    public var tenantId: String?
    /** List of profanity filters */
    public var profanityFilter: [ChatSettingsProfanityFilterInner]?
    /** List of domain filters */
    public var domainFilter: [ChatSettingsDomainFilterInner]?

    public init(tenantId: String? = nil, profanityFilter: [ChatSettingsProfanityFilterInner]? = nil, domainFilter: [ChatSettingsDomainFilterInner]? = nil) {
        self.tenantId = tenantId
        self.profanityFilter = profanityFilter
        self.domainFilter = domainFilter
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case tenantId
        case profanityFilter
        case domainFilter
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(tenantId, forKey: .tenantId)
        try container.encodeIfPresent(profanityFilter, forKey: .profanityFilter)
        try container.encodeIfPresent(domainFilter, forKey: .domainFilter)
    }
}

