//
// Contact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Contact: Codable, JSONEncodable, Hashable {

    /** Name of contact */
    public var name: String
    /** Contact Number */
    public var numbers: [PhoneNumber]?
    /** Contact Email */
    public var emails: [Email]?

    public init(name: String, numbers: [PhoneNumber]? = nil, emails: [Email]? = nil) {
        self.name = name
        self.numbers = numbers
        self.emails = emails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case numbers
        case emails
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(numbers, forKey: .numbers)
        try container.encodeIfPresent(emails, forKey: .emails)
    }
}

