//
// CreateChatReport.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct CreateChatReport: Codable, JSONEncodable, Hashable {

    /** Catgory of Chat Report possible values : other, abuse, spam, inappropriate */
    public var category: String?
    /** detailed reason for raising chat report */
    public var reason: String?

    public init(category: String? = nil, reason: String? = nil) {
        self.category = category
        self.reason = reason
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case reason
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(reason, forKey: .reason)
    }
}

