//
// Email.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Email: Codable, JSONEncodable, Hashable {

    /** Type of Email contact. For example Home/Work */
    public var type: String?
    /** Email */
    public var email: String

    public init(type: String? = nil, email: String) {
        self.type = type
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(email, forKey: .email)
    }
}

