//
// Event.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Event: Codable, JSONEncodable, Hashable {

    public enum EventType: String, Codable, CaseIterable {
        case userselfupdate = "userSelfUpdate"
        case groupupdated = "groupUpdated"
        case chatreportupdated = "chatReportUpdated"
        case chatreaction = "chatReaction"
        case updatemessage = "updateMessage"
        case typingstatus = "typingStatus"
        case chat = "chat"
        case msgreadstatus = "msgReadStatus"
        case availabilitystatus = "availabilityStatus"
    }
    public var eventType: EventType?
    public var message: EventMessage?

    public init(eventType: EventType? = nil, message: EventMessage? = nil) {
        self.eventType = eventType
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventType
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(eventType, forKey: .eventType)
        try container.encodeIfPresent(message, forKey: .message)
    }
}

