//
// FCMValidationInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct FCMValidationInput: Codable, JSONEncodable, Hashable {

    /** FCM Token */
    public var fcmToken: String
    /** Refer https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging#sendToDevice for possible values */
    public var payload: AnyCodable
    /** Refer https://firebase.google.com/docs/reference/admin/node/admin.messaging.Messaging#sendToDevice for possible values */
    public var options: AnyCodable?

    public init(fcmToken: String, payload: AnyCodable, options: AnyCodable? = nil) {
        self.fcmToken = fcmToken
        self.payload = payload
        self.options = options
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case fcmToken
        case payload
        case options
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(fcmToken, forKey: .fcmToken)
        try container.encode(payload, forKey: .payload)
        try container.encodeIfPresent(options, forKey: .options)
    }
}

