//
// Forward.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Forward: Codable, JSONEncodable, Hashable {

    /** msgUniqueId of original chat */
    public var originalMsgUniqueId: String?
    /** to indicate if message is forwarded one or not. */
    public var isForwarded: Bool?

    public init(originalMsgUniqueId: String? = nil, isForwarded: Bool? = nil) {
        self.originalMsgUniqueId = originalMsgUniqueId
        self.isForwarded = isForwarded
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case originalMsgUniqueId
        case isForwarded
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(originalMsgUniqueId, forKey: .originalMsgUniqueId)
        try container.encodeIfPresent(isForwarded, forKey: .isForwarded)
    }
}

