//
// GroupUpdateEventData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GroupUpdateEventData: Codable, JSONEncodable, Hashable {

    /** Optional. Applicable for participantsAdded/participantsRemoved/adminMade/adminDismissed */
    public var eventTriggeredOnUserList: [APIUser]?
    public var changeData: GroupUpdatEventChangeData?

    public init(eventTriggeredOnUserList: [APIUser]? = nil, changeData: GroupUpdatEventChangeData? = nil) {
        self.eventTriggeredOnUserList = eventTriggeredOnUserList
        self.changeData = changeData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventTriggeredOnUserList
        case changeData
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(eventTriggeredOnUserList, forKey: .eventTriggeredOnUserList)
        try container.encodeIfPresent(changeData, forKey: .changeData)
    }
}

