//
// GroupUpdateEventItem.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Group update FCM event item */
public struct GroupUpdateEventItem: Codable, JSONEncodable, Hashable {

    public enum EventType: String, Codable, CaseIterable {
        case created = "created"
        case participantsadded = "participantsAdded"
        case participantsremoved = "participantsRemoved"
        case namechange = "nameChange"
        case profilepicchanged = "profilePicChanged"
        case descriptionchanged = "descriptionChanged"
        case grouptypechanged = "groupTypeChanged"
        case profilepicremoved = "profilePicRemoved"
        case adminmade = "adminMade"
        case admindismissed = "adminDismissed"
    }
    /** Type of the group event. */
    public var eventType: EventType
    public var eventData: GroupUpdateEventData

    public init(eventType: EventType, eventData: GroupUpdateEventData) {
        self.eventType = eventType
        self.eventData = eventData
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eventType
        case eventData
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eventType, forKey: .eventType)
        try container.encode(eventData, forKey: .eventData)
    }
}

