//
// GroupUpdatEventChangeDataName.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Applicable for created/nameChanged/profilePicChanged/descriptionChanged eventTypes */
public struct GroupUpdatEventChangeDataName: Codable, JSONEncodable, Hashable {

    /** Previous value. Applicable only for nameChanged */
    public var previous: String?
    /** new value */
    public var new: String

    public init(previous: String? = nil, new: String) {
        self.previous = previous
        self.new = new
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case previous
        case new
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(previous, forKey: .previous)
        try container.encode(new, forKey: .new)
    }
}

