//
// GroupUpdatEventChangeData.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GroupUpdatEventChangeData: Codable, JSONEncodable, Hashable {

    public var groupId: GroupUpdatEventChangeDataGroupId?
    public var name: GroupUpdatEventChangeDataName?
    public var description: GroupUpdatEventChangeDataName?
    public var profilePic: GroupUpdatEventChangeDataName?
    public var groupType: GroupUpdatEventChangeDataGroupType?

    public init(groupId: GroupUpdatEventChangeDataGroupId? = nil, name: GroupUpdatEventChangeDataName? = nil, description: GroupUpdatEventChangeDataName? = nil, profilePic: GroupUpdatEventChangeDataName? = nil, groupType: GroupUpdatEventChangeDataGroupType? = nil) {
        self.groupId = groupId
        self.name = name
        self.description = description
        self.profilePic = profilePic
        self.groupType = groupType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groupId
        case name
        case description
        case profilePic
        case groupType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(groupId, forKey: .groupId)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(profilePic, forKey: .profilePic)
        try container.encodeIfPresent(groupType, forKey: .groupType)
    }
}

