//
// Invite.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Invite: Codable, JSONEncodable, Hashable {

    public var groupId: String
    public var by: String
    public var to: String
    public var date: String

    public init(groupId: String, by: String, to: String, date: String) {
        self.groupId = groupId
        self.by = by
        self.to = to
        self.date = date
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case groupId
        case by
        case to
        case date
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(groupId, forKey: .groupId)
        try container.encode(by, forKey: .by)
        try container.encode(to, forKey: .to)
        try container.encode(date, forKey: .date)
    }
}

