//
// Location.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Location: Codable, JSONEncodable, Hashable {

    /** Longitude */
    public var longitude: Double?
    /** Latitude */
    public var latitude: Double?
    /** Address of location */
    public var address: String?

    public init(longitude: Double? = nil, latitude: Double? = nil, address: String? = nil) {
        self.longitude = longitude
        self.latitude = latitude
        self.address = address
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case longitude
        case latitude
        case address
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(longitude, forKey: .longitude)
        try container.encodeIfPresent(latitude, forKey: .latitude)
        try container.encodeIfPresent(address, forKey: .address)
    }
}

