//
// LoginPasswordInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct LoginPasswordInput: Codable, JSONEncodable, Hashable {

    /** Type of login  like email/mobile/sso */
    public var loginType: String
    /** User ID based on loginType */
    public var appUserId: String
    /** Current password */
    public var currentPassword: String
    /** New password */
    public var newPassword: String

    public init(loginType: String, appUserId: String, currentPassword: String, newPassword: String) {
        self.loginType = loginType
        self.appUserId = appUserId
        self.currentPassword = currentPassword
        self.newPassword = newPassword
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case loginType
        case appUserId
        case currentPassword
        case newPassword
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(loginType, forKey: .loginType)
        try container.encode(appUserId, forKey: .appUserId)
        try container.encode(currentPassword, forKey: .currentPassword)
        try container.encode(newPassword, forKey: .newPassword)
    }
}

