//
// MessageStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A messages read state, can only be marked as such by recipients in a one to one */
public enum MessageStatus: String, Codable, CaseIterable {
    case delivered = "delivered"
    case seen = "seen"
}
