//
// MessageType.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** A message content type */
public enum MessageType: String, Codable, CaseIterable {
    case text = "text"
    case image = "image"
    case audio = "audio"
    case video = "video"
    case gif = "gif"
    case file = "file"
    case contact = "contact"
    case location = "location"
}
