//
// MessageResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MessageResponse: Codable, JSONEncodable, Hashable {

    public var message: APIMessage?
    public var status: ChatStatus

    public init(message: APIMessage? = nil, status: ChatStatus) {
        self.message = message
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encode(status, forKey: .status)
    }
}

