//
// ModerateGroupInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ModerateGroupInput: Codable, JSONEncodable, Hashable {

    public enum ModelType: String, Codable, CaseIterable {
        case ban = "ban"
        case mute = "mute"
        case unmute = "unmute"
        case unban = "unban"
    }
    public var participants: [String]
    public var type: ModelType
    public var till: String?

    public init(participants: [String], type: ModelType, till: String? = nil) {
        self.participants = participants
        self.type = type
        self.till = till
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case participants
        case type
        case till
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(participants, forKey: .participants)
        try container.encode(type, forKey: .type)
        try container.encodeIfPresent(till, forKey: .till)
    }
}

