//
// NFTLoginInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct NFTLoginInput: Codable, JSONEncodable, Hashable {

    /** wallet address of user */
    public var address: String
    /** contract address of NFT */
    public var contract: String
    /** user wallet signature */
    public var signature: String
    /** token ID of NFT */
    public var tokenID: String
    public var username: String?
    /** The image to use as the user's profile picture */
    public var profilePicture: String?

    public init(address: String, contract: String, signature: String, tokenID: String, username: String? = nil, profilePicture: String? = nil) {
        self.address = address
        self.contract = contract
        self.signature = signature
        self.tokenID = tokenID
        self.username = username
        self.profilePicture = profilePicture
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case address
        case contract
        case signature
        case tokenID
        case username
        case profilePicture
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(address, forKey: .address)
        try container.encode(contract, forKey: .contract)
        try container.encode(signature, forKey: .signature)
        try container.encode(tokenID, forKey: .tokenID)
        try container.encodeIfPresent(username, forKey: .username)
        try container.encodeIfPresent(profilePicture, forKey: .profilePicture)
    }
}

