//
// Participant.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Participant: Codable, JSONEncodable, Hashable {

    public enum Role: String, Codable, CaseIterable {
        case user = "user"
        case admin = "admin"
    }
    /** appUserId of user */
    public var appUserId: String
    /** eRTC user ID of user */
    public var eRTCUserId: String
    /** Role of participant. For example user/admin */
    public var role: Role
    /** Time when user joined */
    public var joinedAtDate: Date

    public init(appUserId: String, eRTCUserId: String, role: Role, joinedAtDate: Date) {
        self.appUserId = appUserId
        self.eRTCUserId = eRTCUserId
        self.role = role
        self.joinedAtDate = joinedAtDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case appUserId
        case eRTCUserId
        case role
        case joinedAtDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(appUserId, forKey: .appUserId)
        try container.encode(eRTCUserId, forKey: .eRTCUserId)
        try container.encode(role, forKey: .role)
        try container.encode(joinedAtDate, forKey: .joinedAtDate)
    }
}

