//
// PhoneNumber.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct PhoneNumber: Codable, JSONEncodable, Hashable {

    /** Type of Number contact. For example Home/Work */
    public var type: String?
    /** Contact Number */
    public var number: String

    public init(type: String? = nil, number: String) {
        self.type = type
        self.number = number
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case number
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(type, forKey: .type)
        try container.encode(number, forKey: .number)
    }
}

