//
// Reaction.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct Reaction: Codable, JSONEncodable, Hashable {

    public var emojiCode: String
    public var count: Int
    public var users: [String]

    public init(emojiCode: String, count: Int, users: [String]) {
        self.emojiCode = emojiCode
        self.count = count
        self.users = users
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case emojiCode
        case count
        case users
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(emojiCode, forKey: .emojiCode)
        try container.encode(count, forKey: .count)
        try container.encode(users, forKey: .users)
    }
}

