//
// ReceiverReturnCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** Return code associated with individual key object. */
public enum ReceiverReturnCode: String, Codable, CaseIterable {
    case receiverkeynotactive = "receiverKeyNotActive"
    case receiverkeyinvalid = "receiverKeyInvalid"
    case receivernewdevicekeyavailable = "receiverNewDeviceKeyAvailable"
}
