//
// ReportStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public enum ReportStatus: String, Codable, CaseIterable {
    case new = "new"
    case reportconsidered = "reportConsidered"
    case reportignored = "reportIgnored"
}
