//
// ReportChannelAdminStatus.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** channel Admin Status */
public struct ReportChannelAdminStatus: Codable, JSONEncodable, Hashable {

    public var status: ReportStatus?
    public var category: ReportCategory?
    /** Chat Report Status creation epoch timeStamp */
    public var createdAt: Double?

    public init(status: ReportStatus? = nil, category: ReportCategory? = nil, createdAt: Double? = nil) {
        self.status = status
        self.category = category
        self.createdAt = createdAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case status
        case category
        case createdAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(status, forKey: .status)
        try container.encodeIfPresent(category, forKey: .category)
        try container.encodeIfPresent(createdAt, forKey: .createdAt)
    }
}

