//
// ResetPasswordInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ResetPasswordInput: Codable, JSONEncodable, Hashable {

    /** Type of login like email/mobile/sso */
    public var loginType: String
    /** User ID based on loginType */
    public var appUserId: String

    public init(loginType: String, appUserId: String) {
        self.loginType = loginType
        self.appUserId = appUserId
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case loginType
        case appUserId
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(loginType, forKey: .loginType)
        try container.encode(appUserId, forKey: .appUserId)
    }
}

