//
// ReturnCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ReturnCode: Codable, JSONEncodable, Hashable {

    public var returnCode: ReceiverReturnCode?

    public init(returnCode: ReceiverReturnCode? = nil) {
        self.returnCode = returnCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case returnCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(returnCode, forKey: .returnCode)
    }
}

