//
// SearchResults.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchResults: Codable, JSONEncodable, Hashable {

    public var messages: [APIMessage]?
    public var files: [APIMessage]?
    public var channels: [APIGroup]?

    public init(messages: [APIMessage]? = nil, files: [APIMessage]? = nil, channels: [APIGroup]? = nil) {
        self.messages = messages
        self.files = files
        self.channels = channels
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case messages
        case files
        case channels
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(messages, forKey: .messages)
        try container.encodeIfPresent(files, forKey: .files)
        try container.encodeIfPresent(channels, forKey: .channels)
    }
}

