//
// SearchQuery.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchQuery: Codable, JSONEncodable, Hashable {

    /** Query string */
    public var text: String?
    /** Thread Id if search target is particular thread. optional. */
    public var threadId: String?
    public var channelQuery: ChannelQuery?

    public init(text: String? = nil, threadId: String? = nil, channelQuery: ChannelQuery? = nil) {
        self.text = text
        self.threadId = threadId
        self.channelQuery = channelQuery
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
        case threadId
        case channelQuery
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(text, forKey: .text)
        try container.encodeIfPresent(threadId, forKey: .threadId)
        try container.encodeIfPresent(channelQuery, forKey: .channelQuery)
    }
}

