//
// SenderReturnCode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** return code for e2e encrypted chat request.  It can be senderKeyValidityExpired (new key to be provided in keyList, also new device key if there)  / receiverKeyValidationError / senderNewDeviceKeyAvailable (new device key to be provided in keyList,  also same device key if validity expired) / success  */
public enum SenderReturnCode: String, Codable, CaseIterable {
    case senderkeyvalidityexpiredComma = "senderKeyValidityExpired,"
    case receiverkeyvalidationerror = "receiverKeyValidationError"
    case sendernewdevicekeyavailable = "senderNewDeviceKeyAvailable"
    case success = "success"
}
