//
// Stub.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/** This does not exist */
public struct Stub: Codable, JSONEncodable, Hashable {

    public var senderKeyDetails: SenderKeyDetails?

    public init(senderKeyDetails: SenderKeyDetails? = nil) {
        self.senderKeyDetails = senderKeyDetails
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case senderKeyDetails
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(senderKeyDetails, forKey: .senderKeyDetails)
    }
}

