//
// SyncContactsInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SyncContactsInput: Codable, JSONEncodable, Hashable {

    public var contacts: [String]

    public init(contacts: [String]) {
        self.contacts = contacts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case contacts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(contacts, forKey: .contacts)
    }
}

