//
// UpdateMessageInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateMessageInput: Codable, JSONEncodable, Hashable {

    /** message text. it can be present for any msgType value */
    public var message: String?
    /** If message is starred */
    public var isStarred: Bool?
    /** Follow/unfollow thread */
    public var follow: Bool?
    public var status: MessageStatus?

    public init(message: String? = nil, isStarred: Bool? = nil, follow: Bool? = nil, status: MessageStatus? = nil) {
        self.message = message
        self.isStarred = isStarred
        self.follow = follow
        self.status = status
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case message
        case isStarred
        case follow
        case status
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(message, forKey: .message)
        try container.encodeIfPresent(isStarred, forKey: .isStarred)
        try container.encodeIfPresent(follow, forKey: .follow)
        try container.encodeIfPresent(status, forKey: .status)
    }
}

