//
// UpdateThreadInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateThreadInput: Codable, JSONEncodable, Hashable {

    public var notificationSettings: NotificationSettings?
    public var autoDeleteSetting: AutoDeleteSettings?

    public init(notificationSettings: NotificationSettings? = nil, autoDeleteSetting: AutoDeleteSettings? = nil) {
        self.notificationSettings = notificationSettings
        self.autoDeleteSetting = autoDeleteSetting
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case notificationSettings
        case autoDeleteSetting
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(notificationSettings, forKey: .notificationSettings)
        try container.encodeIfPresent(autoDeleteSetting, forKey: .autoDeleteSetting)
    }
}

