//
// UpdateGroupInput.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UpdateGroupInput: Codable, JSONEncodable, Hashable {

    public enum GroupType: String, Codable, CaseIterable {
        case _public = "public"
        case _private = "private"
    }
    /** Group Name */
    public var name: String?
    /** Type of group. for example privte/public. only private is supported as of now. */
    public var groupType: GroupType?
    /** Description of group. Optional. Min length 2. */
    public var description: String?
    /** The image for the group */
    public var profilePic: URL?

    public init(name: String? = nil, groupType: GroupType? = nil, description: String? = nil, profilePic: URL? = nil) {
        self.name = name
        self.groupType = groupType
        self.description = description
        self.profilePic = profilePic
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case groupType
        case description
        case profilePic
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(name, forKey: .name)
        try container.encodeIfPresent(groupType, forKey: .groupType)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(profilePic, forKey: .profilePic)
    }
}

