//
// UserSelfUpdateEvent.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserSelfUpdateEvent: Codable, JSONEncodable, Hashable {

    /** User's eRTCUserId */
    public var eRTCUserId: String
    public var eventList: [SelfUpdateItem]

    public init(eRTCUserId: String, eventList: [SelfUpdateItem]) {
        self.eRTCUserId = eRTCUserId
        self.eventList = eventList
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case eRTCUserId
        case eventList
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(eRTCUserId, forKey: .eRTCUserId)
        try container.encode(eventList, forKey: .eventList)
    }
}

