//
// UserInfo.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct UserInfo: Codable, JSONEncodable, Hashable {

    public var user: APIUser
    public var notificationSettings: NotificationSettings?

    public init(user: APIUser, notificationSettings: NotificationSettings? = nil) {
        self.user = user
        self.notificationSettings = notificationSettings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case user
        case notificationSettings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(user, forKey: .user)
        try container.encodeIfPresent(notificationSettings, forKey: .notificationSettings)
    }
}

