# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'IACDemoPods' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for IACDemoPods
  pod "InAppChat"

  target 'IACDemoPodsTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'IACDemoPodsUITests' do
    # Pods for testing
  end

end
